import type { CardDef, CardId } from "./types";

/** Oversight cards. Numbers may be tuned by the engine owner; ids and targets are the contract. */
export const CARDS: Record<CardId, CardDef> = {
  inspect: {
    id: "inspect",
    name: "Inspect",
    cost: 1,
    kind: "skill",
    target: "intent",
    text: "Reveal the evidence behind an intent.",
    flavor: "Trust, but read the logs.",
    icon: "Search",
  },
  block: {
    id: "block",
    name: "Block",
    cost: 1,
    kind: "skill",
    target: "intent",
    text: "Stop an intent. A safe one goes back in the queue.",
    flavor: "“Hold on there, buddy.”",
    icon: "Hand",
  },
  escalate: {
    id: "escalate",
    name: "Escalate",
    cost: 2,
    kind: "skill",
    target: "intent",
    text: "Hand an intent to Dana. She always gets it right.",
    flavor: "Dana has seen things.",
    icon: "ArrowUpRight",
  },
  rollback: {
    id: "rollback",
    name: "Roll Back",
    cost: 2,
    kind: "skill",
    target: "executed",
    text: "Undo a reversible action the agent already took.",
    flavor: "Ctrl+Z, but for your career.",
    icon: "Undo2",
  },
  "policy-callback": {
    id: "policy-callback",
    name: "Policy: Callback",
    cost: 1,
    kind: "power",
    target: "none",
    text: "From now on, credential changes are inspected automatically.",
    flavor: "Guardrails scale. You don't.",
    exhaust: true,
    icon: "ScrollText",
  },
  coffee: {
    id: "coffee",
    name: "Coffee",
    cost: 0,
    kind: "skill",
    target: "none",
    text: "Draw 2 cards.",
    flavor: "The machine works. For now.",
    exhaust: true,
    icon: "Coffee",
  },
};
